image: teeks99/gcc-ubuntu:9 

stages:
        - build
        - testing
        - package

x64.l.gcc.build:
        stage: build
        script:
                - apt-get update
                - apt-get -y install python3 build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
                - echo "alias scons='/usr/bin/env python3 $(which scons)'" >>~/.bashrc
                - scons  platform=x11 tools=yes target=debug
        artifacts:
                paths:
                        - bin/*

x64.l.gcc.testing:
        stage: testing
        script:
                - apt-get update
                - apt-get -y install python3 build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
                - ./bin/godot.linuxbsd.tools.64 --test

x64.l.gcc.package:
        stage: package
        script:
                - apt-get update
                - apt-get -y install python3 build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
                - echo "alias scons='/usr/bin/env python3 $(which scons)'" >>~/.bashrc
                - scons platform=x11 tools=yes target=release
